name: ci
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x, 1.21.x] # when editing, also update steps and job below
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: make test
      - name: Lint
        # Often, lint & gofmt guidelines depend on the Go version. To prevent
        # conflicting guidance, run only on the most recent supported version.
        # For the same reason, only check generated code on the most recent
        # supported version.
        if: matrix.go-version == '1.21.x'
        run: make checkgenerate && make lint
      - name: Run Conformance Tests
        # A dependency of conformance tests (for testing http/3) requires
        # Go 1.20. So we skip this step for Go 1.19.
        if: matrix.go-version != '1.19.x'
        run: make runconformance
  slowtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          # only the latest
          go-version: 1.21.x
      - name: Run Slow Tests
        run: make slowtest